name: build-and-test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: ./tests/download.sh
      - run: cargo test --package relooper
      - run: cargo build
      - run: ./tests/runtest.sh -f tests/glulxercise.ulx -d